### ISSUE TITLE
commonjs import issue

### ISSUE THREAD

**Issue by alextwothousand** [KifKick/altv-typescript-boilerplate#1]
```
[15:57:30] Server started
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
(node:13276) UnhandledPromiseRejectionWarning: ReferenceError: alt is not defined
    at P:\Programming\AltV\PilotsLifeV\resources\pilotslife\server\index.bundle.js:15:1326
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at emitWarning (internal/process/promises.js:120:15)
    at processPromiseRejections (internal/process/promises.js:168:7)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
(node:13276) ReferenceError: alt is not defined
    at P:\Programming\AltV\PilotsLifeV\resources\pilotslife\server\index.bundle.js:15:1326
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:13276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:134:13)
    at emitWarning (internal/process/promises.js:127:3)
    at processPromiseRejections (internal/process/promises.js:168:7)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
    ```

**Comment by KifKick** [comment]
I will take a look tomorrow

**Comment by KifKick** [comment]
Don't know where the issue is because for me it still works. 

```
 ~/altv-typescript-boilerplate  ./start.sh 
[14:41:10] alt:V Server 4.0-dev8 (dev)
[14:41:10] Starting alt:V Server on 0.0.0.0:7788
[14:41:10] Loading resource boilerplate
[14:41:10] Loaded resource boilerplate
[14:41:10] Required server permissions:
[14:41:10] Optional server permissions:
[14:41:10] Starting HTTP server on 0.0.0.0:7788
[14:41:10] Main thread started (ThreadId: 6132)
[14:41:10] Colshape thread started (ThreadId: 6133)
[14:41:10] EntityStreamer thread started (ThreadId: 6145)
[14:41:10] Network thread started (ThreadId: 6147)
[14:41:10] Server started
[14:41:10] Console thread started (ThreadId: 6148)
[14:41:10] Database connected successfully
[14:41:10] exampleFunction of exampleModule loaded
[14:41:10] exampleModule inited
[14:41:10] All modules loaded
```

How did you setup your server? @alextwothousand

**Comment by KifKick** [comment]
No response
